all:
	gcc -x c -Wall -Werror -std=c99 -o out ass4.c -lmkl -liomp5 -lm
band:
	gcc -x c -Wall -Werror -std=c99 -o band band_utility.c -lmkl -liomp5 -lm
lpk:
	gcc -x c -Wall -Werror -std=c99 -o lkp lapk.c -lmkl -liomp5 -lm
	